version: '3.8'
services:
  pingvin-share:
    image: stonith404/pingvin-share
    restart: unless-stopped
# Optional: If you add clamav, uncomment the following to have clamav start first.
#    depends_on:
#      clamav:
#        condition: service_healthy
    ports:
      - 3000:3000
    volumes:
      - "./data:/opt/app/backend/data"
# Optional: Add ClamAV (see README.md)  
# ClamAV is currently only available for AMD64 see https://github.com/Cisco-Talos/clamav/issues/482
#  clamav:
#    restart: unless-stopped
#    image: clamav/clamav
